version: "3.2"

services:
    root612:
        build: .
        image: ncastello/ifcadamic-root612

    rootdocker:
        image: ncastello/ifcadamic-root612    #FIXME: ncastello should be your linux user name
        environment:
            - DISPLAY=unix${DISPLAY}
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
            - type: bind
              source: /home/ncastello/repos/recon  # FIXME: path_to_your_local_directory
              target: /home/rootuser/workdir

